import re
import time
from datetime import datetime
from loguru import logger
from models import AudioMetadata
from config import MAX_DURATION, BLACKLIST_KEYWORDS

# =====================================================================
# IDEA 1: SMART LSD THRESHOLD ENGINE - Ngưỡng LSD động theo năm + tuần
# =====================================================================
ONE_WEEK_SEC = 7 * 24 * 3600

def get_dynamic_min_usage(create_time: int) -> int:
    """Tính ngưỡng LSD tối thiểu dựa theo năm đăng và thời gian gần đây.
    
    Spec:
      - Trong 1 tuần qua  → 300 LSD
      - 2026 (bình thường) → 500 LSD
      - 2025               → 500 LSD
      - 2024               → 500 LSD
      - 2023               → 1000 LSD
      - < 2023             → LOẠI (trừ khi được dùng lại gần đây - xử lý riêng)
    """
    if create_time <= 0:
        return 500  # Không có timestamp → dùng ngưỡng mặc định

    now = time.time()
    if create_time >= now - ONE_WEEK_SEC:
        return 300  # Video trong 1 tuần → threshold thấp nhất

    year = datetime.fromtimestamp(create_time).year
    if year >= 2025: return 500
    if year == 2024: return 500
    if year == 2023: return 1000
    return 999999  # Trước 2023 → không lấy (trừ re-use)


def is_recent_reuse(create_time: int, usage_count: int) -> bool:
    """IDEA 3: Phát hiện audio cũ được dùng lại nhiều gần đây.
    
    Logic: Nếu video cũ (trước 2023) nhưng usage_count rất cao so với tuổi
    thì có thể đang được viral trở lại.
    Ngưỡng: usage_count > 5000 để bù lại tuổi già.
    """
    if create_time <= 0 or usage_count <= 0:
        return False

    year = datetime.fromtimestamp(create_time).year
    if year >= 2023:
        return False  # Không phải "cũ"

    # Video trước 2023, nhưng usage > 5000 → khả năng cao đang được re-use
    return usage_count >= 5000


# =====================================================================
# IDEA 2: SOUND EFFECT DETECTOR - Phát hiện hiệu ứng âm thanh
# =====================================================================
SOUND_EFFECT_KEYWORDS = [
    # Tiếng cười
    "laugh", "laughter", "laughing", "haha", "hehe", "hihi",
    "tiếng cười", "cười", "cười hiệu ứng",
    # Hiệu ứng âm thanh chung
    "sound effect", "sfx", "soundfx", "fx", "hiệu ứng",
    "hiệu ứng âm thanh", "âm hiệu",
    # Tiếng vỗ tay, applause
    "applause", "clapping", "vỗ tay",
    # Nhạc chuông / notification
    "notification", "ringtone", "chuông",
    # Âm thanh game
    "8bit", "8-bit", "chiptune", "game sound",
    # Tiếng động
    "whoosh", "swoosh", "boom", "bang",
]

# Tên chứa các từ này = nhạc nền rõ ràng
BACKGROUND_MUSIC_KEYWORDS = [
    "nhạc nền", "background music", "bgm", "instrumental",
    "no copyright music", "free music", "royalty free",
    "lofi", "lo-fi", "chill music", "study music",
    "ambient", "piano", "guitar", "violin",
]

# Tên/nội dung phim, hoạt hình thương mại, chương trình TV
FILM_TV_KEYWORDS = [
    # Phim/TV
    "phim", "movie", "film", "series", "episode", "tập",
    "trailer", "teaser", "clip phim",
    "drama", "kdrama", "anime",
    # Hoạt hình thương mại (Không phải hoạt hình que)
    "cartoon", "animation studio", "pixar", "disney",
    "dreamworks", "marvel", "dc comics",
    # Chương trình TV có logo
    "gameshow", "game show", "talk show", "variety show",
    "reality show", "award show", "concert",
    # Từ khoá chương trình chuyên nghiệp
    "official mv", "official video", "music video",
]


def has_sound_effect(audio_name: str) -> bool:
    """IDEA 2: Kiểm tra tên audio có phải là hiệu ứng âm thanh không."""
    name_lower = audio_name.strip().lower()
    for kw in SOUND_EFFECT_KEYWORDS:
        if kw in name_lower:
            return True
    return False


def has_background_music_name(audio_name: str) -> bool:
    """IDEA 2: Kiểm tra tên audio có phải là nhạc nền không."""
    name_lower = audio_name.strip().lower()
    for kw in BACKGROUND_MUSIC_KEYWORDS:
        if kw in name_lower:
            return True
    return False


# =====================================================================
# IDEA 4: MEDIA TYPE CLASSIFIER - Phân loại loại nội dung
# =====================================================================

# Keyword gợi ý nội dung AI-generated (được phép lấy với ngưỡng thấp hơn)
AI_GENERATED_KEYWORDS = [
    "ai voice", "ai generated", "ai gen", "text to speech",
    "tts", "ai speaking", "ai narration", "generated by ai",
    "giọng ai", "ai đọc",
]

# Keyword gợi ý game content (được phép với điều kiện)
GAME_KEYWORDS = [
    "gaming", "gameplay", "gamer", "game review",
    "game lore", "reaction game",
]

# Keyword hoạt hình que (cho phép)
STICKMAN_KEYWORDS = [
    "stickman", "stick figure", "stick animation", "que",
    "hoạt hình que",
]

# Keyword podcast không chuyên (cho phép)
PODCAST_ALLOW_KEYWORDS = [
    "podcast", "postcas", "talk show cá nhân",
    "chia sẻ", "kể chuyện", "tâm sự", "vlog",
]

# Keyword phim/TV bị cấm
FILM_TV_BLOCK_KEYWORDS = [
    "phim chiếu rạp", "movie clip", "official film",
    "truyền hình", "vtv", "hbo", "netflix",
    "hoạt hình disney", "marvel clip",
]


def is_allowed_media_type(audio_name: str, author_username: str = "") -> tuple[bool, str]:
    """IDEA 4: Phân loại loại nội dung.
    
    Returns:
        (is_allowed, reason)
    """
    name_lower = audio_name.strip().lower()
    author_lower = author_username.lower()

    # Hard block: phim/TV chuyên nghiệp có logo
    for kw in FILM_TV_BLOCK_KEYWORDS:
        if kw in name_lower:
            return False, f"Blocked media type: film/TV ({kw})"

    # Hard block: kênh chuyên nhạc nền
    blocked_channel_patterns = [
        r"music\s*official", r"^music\d*$", r"beatstore",
        r"soundcloud", r"nhac\s*tru[oa]ng",
    ]
    for pat in blocked_channel_patterns:
        if re.search(pat, author_lower):
            return False, f"Channel blocked: music-only channel"

    return True, "OK"


def get_ai_generated_bonus(audio_name: str) -> bool:
    """Kiểm tra audio có phải AI-generated không (để áp dụng threshold riêng)."""
    name_lower = audio_name.strip().lower()
    for kw in AI_GENERATED_KEYWORDS:
        if kw in name_lower:
            return True
    return False


# =====================================================================
# IDEA 6: MULTI-DIMENSION QUALITY SCORE
# =====================================================================

def compute_quality_score(audio: AudioMetadata) -> float:
    """IDEA 6: Tính điểm chất lượng đa chiều (0.0 - 1.0).
    
    Công thức:
      - speech_ratio     : 40 điểm (tỉ lệ giọng nói)
      - usage_count      : 30 điểm (LSD, chuẩn hoá max 50K)
      - recency          : 20 điểm (video càng gần đây càng cao)
      - original_sound   : 10 điểm (bonus nếu tên có "original sound")
    """
    score = 0.0

    # 1. Speech ratio (40%)
    score += min(audio.speech_ratio, 1.0) * 40.0

    # 2. Usage count (30%) - chuẩn hoá tối đa 50K LSD
    usage_norm = min(max(audio.usage_count, 0) / 50000, 1.0)
    score += usage_norm * 30.0

    # 3. Recency (20%) - năm 2026 = 20đ, năm 2023 = 5đ
    if audio.create_time > 0:
        year = datetime.fromtimestamp(audio.create_time).year
        recency_map = {2026: 20, 2025: 16, 2024: 12, 2023: 5}
        score += recency_map.get(year, 0)
    
    # 4. Original sound bonus (10%)
    name_lower = audio.audio_name.lower()
    if any(p in name_lower for p in ["original sound", "âm thanh gốc", "originalton", "suara asli"]):
        score += 10.0

    # Chuẩn hoá về 0.0 - 1.0
    return round(min(score / 100.0, 1.0), 3)


# =====================================================================
# CORE: Blacklist / CDN / Copyright Helpers (giữ nguyên từ trước)
# =====================================================================
KNOWN_COPYRIGHT_PATTERNS = [
    r"\(\d{7,}\)$",
    r"piano solo", r"music box", r"suspense.*horror", r"horror.*suspense",
    r"lofi version", r"sped up", r"slowed", r"reverb", r"chill vibes",
    r"aesthetic", r"coffee date", r"windy hill", r"morning routine",
    r"a day in my life", r"new sun", r"happy.*pop", r"paint the town red",
    r"like i do", r"can we kiss forever", r"not your girl",
    r"hurt$", r"swim$", r"peace$", r"summer$",
    r"yêu dấu đã về", r"mưa đợi chờ", r"kẹo kẹo gòn",
    r"duyên trời lấy", r"cưa là đổ", r"vó ngựa trên đồi",
    r"hạt mưa vương vấn", r"à lôi", r"nhẹ nhàng khi đọc sách",
    r"cảnh đẹp thiên nhiên", r"^charming$",
    # Cartoon / Anime / TV show characters (bản quyền có sẵn)
    r"stewie", r"family guy", r"brian griffin", r"peter griffin",
    r"spongebob", r"patrick star", r"squidward",
    r"rick and morty", r"south park",
    r"simpsons", r"futurama",
    r"peppa pig", r"paw patrol",
    r"naruto", r"one piece", r"dragon ball",
    r"disney", r"pixar", r"marvel", r"dc comics",
    # Nhạc phim / OST phổ biến
    r"squid game", r"stranger things", r"game of thrones",
    r"breaking bad", r"the office", r"friends theme",
    # Nội dung tôn giáo / nasheed (không dùng thương mại được)
    r"في سبيل الله", r"سبيل الله",      # tiếng Ả Rập "vì Allah"
    r"allahu akbar", r"alhamdulillah",   # Islamic phrases
    r"nasheed", r"نشيد", r"quran",       # nasheed/Islamic content
    r"christian worship", r"gospel",     # Christian worship
    r"hymn", r"praise god", r"hallelujah",
]

TIKTOK_MUSIC_CDN_DOMAINS = [
    "sf16-ies-music-sg.tiktokcdn.com",
    "sf9-ies-music-sg.tiktokcdn.com",
    "sf16-music-sign.tiktokcdn.com",
    "sf3-ttcdn-tos.pstatp.com",
    "p16-sign-sg.tiktokcdn.com",
]

KNOWN_COPYRIGHT_CREATORS = [
    "bgm_farm", "maliabeats", "rawsoundlab", "theokadestudio",
    "rinmusiclofivn", "skymusicncm", "edmlove08", "audiobay",
    "acoustic365", "1998acoustic", "acousticbarlullaby",
    "acoustic.tramhoanghon",
]

SOFT_REJECT_KEYWORDS = [
    "remix", "official", "soundtrack", "instrumental",
    "cover", "karaoke", "lofi", "beat", "prod by",
    "ft.", "feat.", " ost", "bgm", "music by", "composed by",
    # Tiếng Việt — nhạc nền / nhạc phim bị reject
    "nhạc nền", "nhạc phim", "nhạc thiếu nhi", "nhạc không lời",
]

SOFT_ACCEPT_KEYWORDS = [
    "voice", "story", "talk", "react", "pov", "narration",
    "monologue", "speaking", "kể chuyện", "chia sẻ", "tâm sự",
    "cerita", "suara", "história", "voz", "hablar", "contar",
    "reaction", "rant", "confession", "vlog",
]


def is_valid_duration(duration: int) -> bool:
    return 0 < duration <= MAX_DURATION


def is_library_music_url(audio_url: str) -> bool:
    if not audio_url: return False
    for domain in TIKTOK_MUSIC_CDN_DOMAINS:
        if domain in audio_url: return True
    return False


def has_known_copyright_pattern(audio_name: str) -> bool:
    name_lower = audio_name.strip().lower()
    for pattern in KNOWN_COPYRIGHT_PATTERNS:
        if re.search(pattern, name_lower, re.IGNORECASE): return True
    return False


def is_from_known_copyright_creator(video_url: str) -> bool:
    if not video_url: return False
    url_lower = video_url.lower()
    for creator in KNOWN_COPYRIGHT_CREATORS:
        if creator.lower() in url_lower: return True
    return False


def is_blacklisted(audio_name: str) -> bool:
    name_lower = audio_name.lower()
    for word in BLACKLIST_KEYWORDS:
        if re.search(r'\b' + re.escape(word) + r'\b', name_lower) or word in name_lower:
            return True
    return False


def is_original_sound(audio_name: str) -> bool:
    name_lower = audio_name.strip().lower()
    for kw in SOFT_REJECT_KEYWORDS:
        if kw in name_lower: return False
    original_patterns = [
        "âm thanh gốc", "original sound", "originalton",
        "suara asli", "오리지널 사운드", "sonido original",
        "som original", "son original", "เสียงต้นฉบับ",
        "original audio", "my voice", "my sound",
    ]
    for p in original_patterns:
        if p in name_lower: return True
    for kw in SOFT_ACCEPT_KEYWORDS:
        if kw in name_lower: return True
    if len(name_lower) < 60 and not any(bw in name_lower for bw in ["song", "music", "track", "album"]):
        return True
    return False


# =====================================================================
# MAIN PIPELINE - is_valid_audio (đồng bộ) + is_valid_audio_async
# =====================================================================

def is_valid_audio(audio: AudioMetadata) -> tuple[bool, str]:
    """Pipeline lọc đồng bộ - chạy nhanh, không cần await.
    
    Thứ tự kiểm tra:
    1. Validate kiểu dữ liệu cơ bản
    2. Thời lượng hợp lệ (<=59s)
    3. Kiểm tra hiệu ứng âm thanh (IDEA 2)
    4. Kiểm tra nhạc nền qua tên (IDEA 2)
    5. Media type classifier (IDEA 4)
    6. URL không phải CDN nhạc TikTok
    7. Phải là tiếng gốc creator
    8. Không khớp pattern nhạc bản quyền
    9. Không từ creator chuyên nhạc
    10. Không có từ khoá blacklist
    11. Kiểm tra năm + threshold LSD động (IDEA 1)
    """
    if not isinstance(audio.duration, (int, float)) or not isinstance(audio.usage_count, (int, float)):
        return False, "Invalid metadata types"

    if audio.duration <= 0:
        return False, "Duration is zero or negative"

    # 2. Thời lượng
    if not is_valid_duration(audio.duration):
        return False, f"Duration > {MAX_DURATION}s"

    # 3. IDEA 2: Phát hiện hiệu ứng âm thanh (tiếng cười, SFX)
    if has_sound_effect(audio.audio_name):
        return False, "Sound effect detected (tiếng cười / SFX)"

    # 4. IDEA 2: Phát hiện nhạc nền qua tên
    if has_background_music_name(audio.audio_name):
        return False, "Background music name detected"

    # 5. IDEA 4: Phân loại loại nội dung phim/TV cấm
    allowed, media_reason = is_allowed_media_type(audio.audio_name, audio.author_username)
    if not allowed:
        return False, media_reason

    # 6. URL CDN nhạc TikTok
    if is_library_music_url(audio.audio_url):
        return False, "Library music URL (TikTok CDN)"

    # 7. Phải là original sound
    if not is_original_sound(audio.audio_name):
        return False, "Not an original sound"

    # 8. Pattern nhạc bản quyền
    if has_known_copyright_pattern(audio.audio_name):
        return False, "Matches known copyright pattern"

    # 9. Creator chuyên nhạc bản quyền
    if is_from_known_copyright_creator(audio.video_url):
        return False, "From known copyright creator"

    # 10. Blacklist keyword
    if is_blacklisted(audio.audio_name):
        return False, "Blacklisted keyword in name"

    # 11. IDEA 1+3: Kiểm tra năm và ngưỡng LSD động
    usage = audio.usage_count if audio.usage_count != -1 else 0
    create_time = audio.create_time

    # Kiểm tra video trước 2023
    if create_time > 0 and create_time < 1672531200:  # 2023-01-01
        # IDEA 3: Re-use exception - video cũ nhưng usage cao bất thường
        if is_recent_reuse(create_time, usage):
            logger.debug(f"Re-use detected: {audio.audio_name} ({usage:,} LSD)")
            # Cho qua nhưng đặt usage_count để check_usage xác nhận lại
        else:
            return False, "Video created before 2023 (no reuse signal)"

    # Áp dụng ngưỡng LSD động (chỉ reject nếu tool đã biết usage)
    if usage != 0:  # usage=0 hoặc -1 → chưa biết → để Phase 2 check
        min_required = get_dynamic_min_usage(create_time)
        if usage < min_required:
            year = datetime.fromtimestamp(create_time).year if create_time > 0 else "?"
            return False, f"LSD {usage:,} < {min_required:,} (yêu cầu cho năm {year})"

    return True, "Valid"


async def is_valid_audio_async(audio: AudioMetadata) -> tuple[bool, str]:
    """Bản async của pipeline lọc - có thêm kiểm tra tác giả từ DB/Sheet.
    Gọi hàm này nếu cần check đầy đủ bao gồm DB lookup.
    """
    # Chạy pipeline đồng bộ trước
    ok, reason = is_valid_audio(audio)
    if not ok:
        return False, reason

    # Bổ sung: Lọc tác giả đã biết (2 tuần)
    from database import is_author_known
    if await is_author_known(audio.author_username):
        two_weeks_ago = int(time.time()) - (14 * 24 * 60 * 60)
        if audio.create_time > 0 and audio.create_time < two_weeks_ago:
            return False, "Known author, video older than 2 weeks"

    return True, "Valid"
